url: "https://naturecodevoid.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "naturecodevoid.dev"
description: "naturecodevoid's website :)"
exclude: [README.md, scripts/, _templates/]
